name: shakesphere
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  curl_logger_dio_interceptor: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications:
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  handy_extensions: ^0.2.2
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  jwt_decode: ^0.3.1
  localregex:
  modal_bottom_sheet: ^3.0.0-pre
  network_info_plus: ^4.0.2
  permission_handler:
  pretty_dio_logger: ^1.3.1
  relative_scale: ^2.0.0
  sentry_dio: ^7.18.0
  sentry_flutter: ^7.18.0
  shared_preferences: ^2.2.1
  vibration:

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator:
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: 'NunitoSans'
      fonts:
        - asset: fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/NunitoSans-Black.ttf
          weight: 900
